name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'sbt'

    - uses: sbt/setup-sbt@v1

    - run: sbt test
    - run: sbt scripted
    - run: sbt publishLocal
    - run: src/reqs/check.sh
